name: DevOps CI Pipeline

on:
push:
branches:
- main
pull_request:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Show project structure
    run: ls -R

  - name: Validate HTML file
    run: |
      if [ ! -f app/index.html ]; then
        echo "index.html not found!"
        exit 1
      fi
      echo "HTML file exists."

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: website-files
      path: app/
```
